# http://travis-ci.org/#!/ipython/ipython
language: python
cache:
    directories:
        - ~/.cache/bower
python:
    - 3.5
    - 2.7
sudo: false
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
    - GROUP=python
before_install:
    - 'if [[ $GROUP == js* ]]; then npm install -g casperjs; fi'
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse --pre file://$PWD#egg=notebook[test] coveralls
script:
    - python -c 'import os, pprint; pprint.pprint(dict(os.environ))'
    - 'if [[ $GROUP == js* ]]; then python -m notebook.jstest ${GROUP:3}; fi'
    - 'if [[ $GROUP == python ]]; then nosetests --with-coverage --cover-package=notebook notebook; fi'
