branches:
  matrix:
    fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - CONDA_PY: 27
    - CONDA_PY: 35

platform:
  - x64

build: off

install:
  # miniconda bootstrap from conda-forge recipe
  - appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
  - cmd: python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  - cmd: conda install pyzmq tornado jupyter_client nbformat nbconvert ipykernel pip nodejs nosetests
  - cmd: pip install -vv .[test]

test_script:
  - nosetests -vsx notebook
